In [2]:
    import numpy as np
    
    t = np.arange(0.0, 10.0, 0.01)


In [3]:
t

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
        0.18,  0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,
        0.27,  0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,
        0.36,  0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,
        0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,
        0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,
        0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,
        0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
        0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,
        0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,
        0.99,  1.  ,  1.01,  1.02,  1.03,  1.04,  1.05,  1.06,  1.07,
        1.08,  1.09,  1.1 ,  1.11,  1.12,  1.13,  1.14,  1.15,  1.16,
        1.17,  1.18,  1.19,  1.2 ,  1.21,  1.22,  1.23,  1.24,  1.25,
        1.26,  1.27,

In [7]:
from numpy import sin,pi,arange,random
wave1 = sin(2 * 2 * pi * t)

In [8]:
wave1

array([  0.00000000e+00,   1.25333234e-01,   2.48689887e-01,
         3.68124553e-01,   4.81753674e-01,   5.87785252e-01,
         6.84547106e-01,   7.70513243e-01,   8.44327926e-01,
         9.04827052e-01,   9.51056516e-01,   9.82287251e-01,
         9.98026728e-01,   9.98026728e-01,   9.82287251e-01,
         9.51056516e-01,   9.04827052e-01,   8.44327926e-01,
         7.70513243e-01,   6.84547106e-01,   5.87785252e-01,
         4.81753674e-01,   3.68124553e-01,   2.48689887e-01,
         1.25333234e-01,   1.22464680e-16,  -1.25333234e-01,
        -2.48689887e-01,  -3.68124553e-01,  -4.81753674e-01,
        -5.87785252e-01,  -6.84547106e-01,  -7.70513243e-01,
        -8.44327926e-01,  -9.04827052e-01,  -9.51056516e-01,
        -9.82287251e-01,  -9.98026728e-01,  -9.98026728e-01,
        -9.82287251e-01,  -9.51056516e-01,  -9.04827052e-01,
        -8.44327926e-01,  -7.70513243e-01,  -6.84547106e-01,
        -5.87785252e-01,  -4.81753674e-01,  -3.68124553e-01,
        -2.48689887e-01,

In [16]:
    print(wave1.size)
    noise = random.normal(0, 0.1, len(t))
    wave1 = wave1 + noise
    print("wave1", len(wave1))
    wave2 = sin(2 * pi * t)
    print("wave2", len(wave2))
    t_rider = arange(0.0, 0.5, 0.01)
    wave3 = sin(10 * pi * t_rider)
    print("wave3", len(wave3))
    insert = round(0.8 * len(t))
    wave1[insert:insert + 50] = wave1[insert:insert + 50] + wave3


1000
('wave1', 1000)
('wave2', 1000)
('wave3', 50)


/usr/lib/python2.7/site-packages/ipykernel/__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [10]:
mani = wave1 + wave2

In [11]:
mani

array([  9.39791411e-02,   3.22971185e-01,   3.12562882e-01,
         2.89417470e-01,   6.98333225e-01,   8.06423638e-01,
         8.77365497e-01,   1.25942994e+00,   1.38819189e+00,
         1.38979959e+00,   1.35017788e+00,   1.62707414e+00,
         1.76805269e+00,   1.80951739e+00,   1.72282552e+00,
         1.73159028e+00,   1.72624652e+00,   1.74983708e+00,
         1.76209348e+00,   1.42352004e+00,   1.62228817e+00,
         1.53219986e+00,   1.35126928e+00,   1.08221809e+00,
         1.16026372e+00,   1.08866128e+00,   8.48558228e-01,
         7.90385040e-01,   4.39125545e-01,   2.46723583e-01,
         2.41969715e-01,   2.57681125e-01,   1.09485106e-01,
        -4.16888076e-02,  -1.31888369e-01,  -1.97799440e-01,
        -3.58584437e-01,  -3.43242615e-01,  -2.01693754e-01,
        -4.51917520e-01,  -4.47646760e-01,  -4.80358500e-01,
        -2.92510288e-01,  -3.10348381e-01,  -3.19288074e-01,
        -2.94062618e-01,  -2.02968508e-01,  -1.07790110e-01,
        -3.29702739e-01,

In [14]:
mani.size

1000

In [17]:
len(mani)

1000

In [18]:
result = []
for index in range(0, 700 - 100):
    result.append(mani[index: index + 100])

In [21]:
result = np.array(result) 

In [23]:
result.shape

(600, 100)